### ISSUE TITLE
I am seeing an issue in the emotion service

### ISSUE THREAD

**Issue by Nabarun** [joshbalfour/node-cognitive-services#1]
I am seeing this issue in the cognitive-service is this known?

node_modules/cognitive-services/api/academicKnowledge.js:1
(function (exports, require, module, __filename, __dirname) { const {
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/nabarunsengupta/Documents/workspace/runu/node_modules/cognitive-services/api/index.js:2:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by yenta** [comment]
same problem as well,how to fix it?

**Comment by Nabarun** [comment]
I eventually had to use gcloud nodejs as I was not getting any support in here.

**Comment by joshbalfour** [comment]
which version of node JS are you using?

**Comment by yenta** [comment]
v5.5.0

**Comment by julietsvq** [comment]
I had the same error, updated to the latest version and now it´s ok

**Comment by joshbalfour** [comment]
fixed by enforcing minimum node version in `package.json`
