### ISSUE TITLE
Can't import cognitive services

### ISSUE THREAD

**Issue by latagore** [joshbalfour/node-cognitive-services#24]
I'm using node 6.11.3 and cognitive-services 0.3.1. `xmlBuilder` should be `xmlbuilder`

Steps:
1. Include `cognitive-services`:
```require('cognitive-services');```
2. See error:
```
Error: Cannot find module 'xmlBuilder'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/nexxt/bot/node_modules/cognitive-services/dist/language/textTranslator.js:11:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/nexxt/bot/node_modules/cognitive-services/dist/index.js:21:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/nexxt/bot/test4.js:1:63)
    at Module._compile (module.js:570:32)
```

**Comment by miparnisari** [comment]
Thanks for the bug report and for fixing it :)

**Comment by miparnisari** [comment]
@latagore version 0.3.2 is out with the fix.
