### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by IanMoritz** [joshbalfour/node-cognitive-services#7]
I'm running into a syntax error when using spell check

`node_modules/cognitive-services/api/academicKnowledge.js:1
(function (exports, require, module, __filename, __dirname) { const {
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/node_modules/cognitive-services/api/index.js:2:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

**Comment by haitch** [comment]
I am having same issue.

**Comment by devsavage** [comment]
This should be fixed if you are using node 6 or higher.

**Comment by haitch** [comment]
thanks, it does solve my issue.

**Comment by miparnisari** [comment]
@joshbalfour please mark this as resolved :)
