### ISSUE TITLE
Syntax Error with ComputerVision

### ISSUE THREAD

**Issue by kdupreez** [joshbalfour/node-cognitive-services#8]
/Code/node/cognitive/node_modules/cognitive-services/api/academicKnowledge.js:1
(function (exports, require, module, __filename, __dirname) { const {
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/koos/Desktop/Dropbox/Private/Code/node/cognitive/node_modules/cognitive-services/api/index.js:2:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
KoosMac-K2-2:cognitive koos$

**Comment by devsavage** [comment]
This should be fixed if you are using node 6 or higher.

**Comment by miparnisari** [comment]
@joshbalfour please mark this is as resolved :)
